In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(input_dim, units), dtype="float32"),
            trainable=True,
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(units,), dtype="float32"), trainable=True
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

In [4]:
x = tf.ones((2, 2))

In [5]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [6]:
linear_layer = Linear(4, 2)

In [7]:
y = linear_layer(x)

In [8]:
print(y)

tf.Tensor(
[[-0.01359961  0.0665551  -0.01611071  0.03288155]
 [-0.01359961  0.0665551  -0.01611071  0.03288155]], shape=(2, 4), dtype=float32)
