In [ ]:
import tensorflow as tf
from matplotlib import pyplot as plt

In [ ]:
plt.rcParams['font.size'] = 16
plt.rcParams['font.family'] = ['STKaiti']
plt.rcParams['axes.unicode_minus'] = False

In [ ]:
# 创建 W,b 张量
x = tf.random.normal([2,5])
w1 = tf.Variable(tf.random.truncated_normal([5, 10], stddev=0.1))
b1 = tf.Variable(tf.ones([10]))

In [ ]:
x.shape

TensorShape([2, 5])

In [ ]:
x

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 0.9603022 ,  0.83019936,  0.6645588 ,  0.61551654, -0.01789901],
       [ 0.06809555, -0.3022149 , -0.01588861,  2.1857028 , -0.8113959 ]],
      dtype=float32)>

In [ ]:
w1.shape

TensorShape([5, 10])

In [ ]:
w1

<tf.Variable 'Variable:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.10207744, -0.08792242, -0.10643263,  0.00519138,  0.0468709 ,
         0.12437171,  0.02414432,  0.10478854,  0.00790195,  0.05299341],
       [ 0.14994673, -0.03302911, -0.07381869, -0.08884042,  0.04294717,
        -0.12653068, -0.17531738,  0.12302207,  0.08941293, -0.06098759],
       [ 0.05411225,  0.08099547,  0.00239847, -0.17154105, -0.13833036,
         0.08101197, -0.10532776,  0.03379022,  0.05059404,  0.08282928],
       [-0.11749562, -0.14213137, -0.00053152,  0.02945859, -0.18933596,
        -0.17172113, -0.09952335,  0.16082254,  0.02820495,  0.07948216],
       [-0.07555396, -0.03946165, -0.04304051, -0.12664418,  0.11294513,
         0.00354131, -0.02994685,  0.05042721,  0.01782449,  0.01655318]],
      dtype=float32)>

In [ ]:
b1.shape

TensorShape([10])

In [ ]:
b1

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
o1 = tf.matmul(x,w1)
o1

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.18750349, -0.14480446, -0.16145457, -0.16237003, -0.12982474,
        -0.03753464, -0.25308126,  0.32330343,  0.13248311,  0.10392906],
       [-0.23473123, -0.27593005,  0.04878456,  0.19707423, -0.51306504,
        -0.3327833 , -0.13692856,  0.28001347,  0.01989723,  0.18101713]],
      dtype=float32)>

In [ ]:
# 线性变换
o1 = tf.matmul(x,w1) + b1
o1

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1.1875035 , 0.8551955 , 0.83854544, 0.83763   , 0.87017524,
        0.96246535, 0.74691874, 1.3233035 , 1.1324831 , 1.103929  ],
       [0.7652688 , 0.72406995, 1.0487846 , 1.1970742 , 0.48693496,
        0.66721666, 0.86307144, 1.2800134 , 1.0198972 , 1.1810172 ]],
      dtype=float32)>

In [ ]:
o1

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1.1875035 , 0.8551955 , 0.83854544, 0.83763   , 0.87017524,
        0.96246535, 0.74691874, 1.3233035 , 1.1324831 , 1.103929  ],
       [0.7652688 , 0.72406995, 1.0487846 , 1.1970742 , 0.48693496,
        0.66721666, 0.86307144, 1.2800134 , 1.0198972 , 1.1810172 ]],
      dtype=float32)>

In [ ]:
# 激活函数
o1 = tf.nn.relu(o1)

In [ ]:
o1

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1.1875035 , 0.8551955 , 0.83854544, 0.83763   , 0.87017524,
        0.96246535, 0.74691874, 1.3233035 , 1.1324831 , 1.103929  ],
       [0.7652688 , 0.72406995, 1.0487846 , 1.1970742 , 0.48693496,
        0.66721666, 0.86307144, 1.2800134 , 1.0198972 , 1.1810172 ]],
      dtype=float32)>

In [ ]:
x = tf.random.normal([4,28*28])

In [ ]:
# 导入层模块
from tensorflow.keras import layers

In [ ]:
# 创建全连接层，指定输出节点数和激活函数
fc = layers.Dense(512, activation=tf.nn.relu)

In [ ]:
# 通过 fc 类实例完成一次全连接层的计算，返回输出张量
h1 = fc(x)
h1

<tf.Tensor: shape=(4, 512), dtype=float32, numpy=
array([[1.8731356 , 0.        , 1.8574799 , ..., 0.        , 0.6788043 ,
        0.17816591],
       [1.2820723 , 0.07679738, 1.2154546 , ..., 0.05584311, 1.1987467 ,
        0.        ],
       [0.        , 0.        , 1.3025131 , ..., 0.        , 1.9007425 ,
        0.01764208],
       [0.        , 0.        , 0.5586759 , ..., 0.        , 2.0304675 ,
        1.1567775 ]], dtype=float32)>

In [ ]:
h1.shape

TensorShape([4, 512])

In [ ]:
# 获取 Dense 类的权值矩阵
print(fc.kernel)
# 获取 Dense 类的偏置向量
print(fc.bias)
# 待优化参数列表
print(fc.trainable_variables)
# 返回所有参数列表
print(fc.variables)

<Variable path=dense_1/kernel, shape=(784, 512), dtype=float32, value=[[-0.02760638  0.05575391  0.00150662 ... -0.05848197 -0.03964124
  -0.02426914]
 [-0.03745361  0.02365926 -0.02630363 ...  0.05649843 -0.03401458
   0.04691949]
 [-0.04088494  0.04232427  0.05390918 ... -0.02814139 -0.05033696
  -0.04038478]
 ...
 [-0.0181361  -0.00180238  0.06152539 ... -0.03831075  0.06430805
  -0.03845445]
 [ 0.03224834  0.03529681 -0.02469555 ... -0.02614558  0.04750974
  -0.0474347 ]
 [-0.01101775 -0.02393081 -0.00108542 ... -0.02498711  0.06109421
   0.00640339]]>
<Variable path=dense_1/bias, shape=(512,), dtype=float32, value=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0

In [ ]:
# 隐藏层 1 张量
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
# 隐藏层 2 张量
w2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
# 隐藏层 3 张量
w3 = tf.Variable(tf.random.truncated_normal([128, 64], stddev=0.1))
b3 = tf.Variable(tf.zeros([64]))
# 输出层张量
w4 = tf.Variable(tf.random.truncated_normal([64, 10], stddev=0.1))
b4 = tf.Variable(tf.zeros([10]))

In [ ]:
with tf.GradientTape() as tape: # 梯度记录器
    # x: [b, 28*28]
    # 隐藏层 1 前向计算， [b, 28*28] => [b, 256]
    h1 = x@w1 + tf.broadcast_to(b1, [x.shape[0], 256])
    h1 = tf.nn.relu(h1)
    # 隐藏层 2 前向计算， [b, 256] => [b, 128]
    h2 = h1@w2 + b2
    h2 = tf.nn.relu(h2)
    # 隐藏层 3 前向计算， [b, 128] => [b, 64]
    h3 = h2@w3 + b3
    h3 = tf.nn.relu(h3)
    # 输出层前向计算， [b, 64] => [b, 10]
    h4 = h3@w4 + b4

In [ ]:
import tensorflow as tf

# 定义模型参数
w1 = tf.Variable(tf.random.normal([784, 256]))
b1 = tf.Variable(tf.zeros([256]))
w2 = tf.Variable(tf.random.normal([256, 128]))
b2 = tf.Variable(tf.zeros([128]))
w3 = tf.Variable(tf.random.normal([128, 64]))
b3 = tf.Variable(tf.zeros([64]))
w4 = tf.Variable(tf.random.normal([64, 10]))
b4 = tf.Variable(tf.zeros([10]))

# 输入数据
x = tf.random.normal([32, 784])  # 假设有32个样本，每个样本784维

# 使用梯度记录器
with tf.GradientTape() as tape:
    # 前向传播
    h1 = x @ w1 + b1
    h1 = tf.nn.relu(h1)
    h2 = h1 @ w2 + b2
    h2 = tf.nn.relu(h2)
    h3 = h2 @ w3 + b3
    h3 = tf.nn.relu(h3)
    h4 = h3 @ w4 + b4
    # 假设 h4 是输出，计算损失（例如交叉熵损失）
    loss = tf.nn.softmax_cross_entropy_with_logits(labels=tf.one_hot(tf.random.uniform([32], maxval=10, dtype=tf.int32), 10), logits=h4)
    loss = tf.reduce_mean(loss)

# 计算梯度
grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3, w4, b4])

# 打印梯度
for grad in grads:
    print(grad.shape)